/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerosRouteImport } from './routes/generos'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeneroSlugRouteImport } from './routes/genero.$slug'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as VerIdEpisodeIdRouteImport } from './routes/ver.$id.$episodeId'

const GenerosRoute = GenerosRouteImport.update({
  id: '/generos',
  path: '/generos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneroSlugRoute = GeneroSlugRouteImport.update({
  id: '/genero/$slug',
  path: '/genero/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerIdEpisodeIdRoute = VerIdEpisodeIdRouteImport.update({
  id: '/ver/$id/$episodeId',
  path: '/ver/$id/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/catalogo': typeof CatalogoRoute
  '/generos': typeof GenerosRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genero/$slug': typeof GeneroSlugRoute
  '/ver/$id/$episodeId': typeof VerIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/catalogo': typeof CatalogoRoute
  '/generos': typeof GenerosRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genero/$slug': typeof GeneroSlugRoute
  '/ver/$id/$episodeId': typeof VerIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/catalogo': typeof CatalogoRoute
  '/generos': typeof GenerosRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genero/$slug': typeof GeneroSlugRoute
  '/ver/$id/$episodeId': typeof VerIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/catalogo'
    | '/generos'
    | '/anime/$id'
    | '/genero/$slug'
    | '/ver/$id/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/catalogo'
    | '/generos'
    | '/anime/$id'
    | '/genero/$slug'
    | '/ver/$id/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/catalogo'
    | '/generos'
    | '/anime/$id'
    | '/genero/$slug'
    | '/ver/$id/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CatalogoRoute: typeof CatalogoRoute
  GenerosRoute: typeof GenerosRoute
  AnimeIdRoute: typeof AnimeIdRoute
  GeneroSlugRoute: typeof GeneroSlugRoute
  VerIdEpisodeIdRoute: typeof VerIdEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generos': {
      id: '/generos'
      path: '/generos'
      fullPath: '/generos'
      preLoaderRoute: typeof GenerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genero/$slug': {
      id: '/genero/$slug'
      path: '/genero/$slug'
      fullPath: '/genero/$slug'
      preLoaderRoute: typeof GeneroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ver/$id/$episodeId': {
      id: '/ver/$id/$episodeId'
      path: '/ver/$id/$episodeId'
      fullPath: '/ver/$id/$episodeId'
      preLoaderRoute: typeof VerIdEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CatalogoRoute: CatalogoRoute,
  GenerosRoute: GenerosRoute,
  AnimeIdRoute: AnimeIdRoute,
  GeneroSlugRoute: GeneroSlugRoute,
  VerIdEpisodeIdRoute: VerIdEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
